# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  RepoSecret:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - shell: bash
      env:
        SECRET_REPO: ${{ secrets.SECRETREPO }}
        SECRET_ENVIRONMENT: ${{ secrets.SECRETENV }}
      run: |
        echo "$SECRET_REPO"
        echo "$SECRET_ENVIRONMENT"

  EnvSecret:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ActionEnv
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - shell: bash
      env:
        SECRET_REPO: ${{ secrets.SECRETREPO }}
        SECRET_ENVIRONMENT: ${{ secrets.SECRETENV }}
      run: |
        echo "$SECRET_REPO"
        echo "$SECRET_ENVIRONMENT"
